### ISSUE TITLE
Multiple Errors with CMakeList.txt files

### ISSUE THREAD

**Issue by HaleyCurr** [rosmod/rosmod-comm#3] opened 2017-07-05 15:58 UTC
I was using catkin_build to build the packages, and my supervisor and I kept on running into errors with the CMakeList.txt files in rosmod_jsonccp, rosmod_component, and rosmod_actor. We changed them to work, and forked and pushed our files to this repository: https://github.com/HaleyCurr/rosmod-comm .

**Comment by finger563** [comment] 2017-07-05 16:19
I'd recommend not pushing the `build` `devel` `.catkin-tools`, and `logs` directories into git. If you remove those from your git (not just delete them, but alter the commit so they don't exist in the repo at all) then I can more easily take a look at your changes and could handle a pull request from your fork :)

**Comment by finger563** [comment] 2017-07-05 16:22
And can you be more specific about the errors you were getting? We've not had errors on our end building and installing fresh on new systems.

**Comment by HaleyCurr** [comment] 2017-07-05 17:22
Sure, and I'll fix the repo momentarily. 

When building rosmod_jsoncpp:
> CMake Error at /home/haley/WebGME/rosmod-comm/src/rosmod_jsoncpp/CMakeLists.txt:81 (catkin_package):
>  Unknown CMake command "catkin_package".

When building rosmod_component:
> /usr/bin/ld: cannot find -lrosmod_jsoncpp
> collect2: error: ld returned 1 exit status
> CMakeFiles/rosmod_component.dir/build.make:113: recipe for target '/home/haley/WebGME/rosmod-comm/devel/.private/rosmod_component/lib/librosmod_component.so' failed
> make[2]: *** [/home/haley/WebGME/rosmod-comm/devel/.private/rosmod_component/lib/librosmod_component.so] Error 1
CMakeFiles/Makefile2:707: recipe for target 'CMakeFiles/rosmod_component.dir/all' failed
> make[1]: *** [CMakeFiles/rosmod_component.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2

When building rosmod_actor:
> /usr/bin/ld: cannot find -lrosmod_component
> /usr/bin/ld: cannot find -lrosmod_jsoncpp
> collect2: error: ld returned 1 exit status
> CMakeFiles/rosmod_actor.dir/build.make:115: recipe for target '/home/haley/WebGME/rosmod-comm/devel/.private/rosmod_actor/lib/rosmod_actor/rosmod_actor' failed
> make[2]: *** [/home/haley/WebGME/rosmod-comm/devel/.private/rosmod_actor/lib/rosmod_actor/rosmod_actor] Error 1
CMakeFiles/Makefile2:707: recipe for target 'CMakeFiles/rosmod_actor.dir/all' failed
> make[1]: *** [CMakeFiles/rosmod_actor.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by finger563** [comment] 2017-07-05 17:40
That looks like you're getting a lot of errors stemming from your ROS environment not being properly set up, since the `find_package( catkin )` seems to be failing, which ROS version are you using it with and how did you configure your ROS environment?

**Comment by finger563** [comment] 2017-07-05 17:42
Though you do seem to have found a bug, which is that the [ROSMOD_jsoncpp's CMakeLists.txt](https://github.com/rosmod/rosmod-comm/blob/master/src/rosmod_jsoncpp/CMakeLists.txt) doesn't have `find_package( catkin )` as it should.  Try adding just that and it should work for you.  An example is in [ROSMOD_component's CMakeList.txt](https://github.com/rosmod/rosmod-comm/blob/master/src/rosmod_component/CMakeLists.txt#L16)

**Comment by HaleyCurr** [comment] 2017-07-05 18:04
My ROS enviornment is kinetic. Okay, we've redone the repo to only include the src. When we added the `find_package` to the jsonccp, we ran into the the error with `rosmod_components` (because it was next on the build list). We fixed that by making the `rosmod_jsonccp` a required package instead of a linked library. Next on the list was `rosmod_actor`, which had the same error. We made jsonccp and components required packages instead of linked libraries there.

**Comment by finger563** [comment] 2017-07-05 18:10
By removing them as linked libraries I think you'll find that actually running the `rosmod_actor` fails or at the very least trying to start a component within the `rosmod_actor` will fail, since the libraries will not be loaded.  I can add them as required packages to ensure the build works fine, but they'll still need to be linked properly otherwise they'll need to be dynamically loaded within the code.

**Comment by finger563** [comment] 2017-07-05 18:16
@HaleyCurr I've just pushed a fix that I tested with an install of `ROS Kinetic`, please let me know if it fixes the build issue you're having as well

**Comment by HaleyCurr** [comment] 2017-07-05 18:17
Alright. I'll add them back as linked libraries. I'll see about the fix.

**Comment by HaleyCurr** [comment] 2017-07-05 18:32
New error popped up when building with your fix.
> /usr/bin/ld: cannot find -lrosmod_jsoncpp
> collect2: error: ld returned 1 exit status
> make[2]: *** [/home/haley/WebGME/catkin_ws/devel/.private/rosmod_component/lib/librosmod_component.so] Error 1
> make[1]: *** [CMakeFiles/rosmod_component.dir/all] Error 2
> make: *** [all] Error 2
> cd /home/haley/WebGME/catkin_ws/build/rosmod_component; catkin build --get-env rosmod_component | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -

**Comment by finger563** [comment] 2017-07-05 18:33
Can you attach a file with the full output of your build?

**Comment by finger563** [comment] 2017-07-05 18:36
And you should be able to find the built `rosmod_jsoncpp` shared object within `${ROS INSTALL LOCATION}/lib/` as `librosmod_jsoncpp.so`, e.g. `/opt/ros/kinetic/lib/librosmod_jsoncpp.so`

**Comment by HaleyCurr** [comment] 2017-07-05 18:37
[build.output.001.txt](https://github.com/rosmod/rosmod-comm/files/1125678/build.output.001.txt)

**Comment by finger563** [comment] 2017-07-05 18:39
Can you make sure that you have full write permissions to `/opt/ros/kinetic`? it seems to be building just fine, but then not able to find the library.  It seems you're using a slightly different build system or different cmake version than I am, so it isn't printing out all the information I usually see (which shows it actually installing the SO into the right directory).  Can you see if you can find the SO as per my previous comment? according to your log it should be in `/opt/ros/kinetic/lib/librosmod_jsoncpp.so`

**Comment by HaleyCurr** [comment] 2017-07-05 18:44
It seems i do not have` librosmod_jsonccp.so`. I have full write permissions tho.

**Comment by finger563** [comment] 2017-07-05 18:46
Can you provide more information about the system you're compiling on so I can try to replicate it, i.e. what OS, arch, build system, versions etc.?

**Comment by p-ranav** [comment] 2017-07-05 18:47
Are you able to successfully build rosmod_jsoncpp at all?

**Comment by finger563** [comment] 2017-07-05 18:48
Here is an example build on a fresh system: (no rosmod)
[buildSuccess.txt](https://github.com/rosmod/rosmod-comm/files/1125708/buildSuccess.txt)

(actually that was the second build on the fresh system, but similar output ;) )

**Comment by HaleyCurr** [comment] 2017-07-05 18:52
Ubuntu 16.04
ROS Kinetic Kame
Aside from these, I don't know the exact specs myself; however, I just pointed my supervisor/professor to this issue so he can catch up. 

At this point, rosmod_jsonccp builds. We just have an error with rosmod_components not finding a library.

**Comment by dcconner** [comment] 2017-07-05 18:54
Our set up does not write the files to /opt/ros/kinetic.  That is a protected folder for us.
@HaleyCurr fix requires that rosmod_jsoncpp is a catkin package, then depends on catkin to set up the path correctly.   Listing the library separate as was originally done, forces it to be in a standard library path.

**Comment by finger563** [comment] 2017-07-05 18:54
Hmm, I'm 16.04 with Kinetic as well. What build system are you using? it appears to be quite different from the one I use, and I imagine that's where the source of the problem is.

**Comment by p-ranav** [comment] 2017-07-05 18:55
You *are* searching for rosmod_jsoncpp and not rosmod_jsonccp right? I've seen you mistype this twice now.

**Comment by HaleyCurr** [comment] 2017-07-05 18:56
Yea, I just have English problems.

**Comment by HaleyCurr** [comment] 2017-07-05 18:56
Its Json c++

**Comment by finger563** [comment] 2017-07-05 18:57
@dcconner if you're not able to install to `/opt/ros/kinetic`, then we'll need to have it install to somewhere you do have permissions to write into.

**Comment by p-ranav** [comment] 2017-07-05 18:59
No problem. Just a sanity check.

**Comment by HaleyCurr** [comment] 2017-07-05 18:59
Its all good.

**Comment by p-ranav** [comment] 2017-07-05 19:00
Can you echo $ROS_PACKAGE_PATH and see if where ever jsoncpp is installed is part of this path?

**Comment by dcconner** [comment] 2017-07-05 19:01
@HaleyCurr and I are using the "catkin tools" build system.   Under a normal catkin setup, the built libraries are installed under the devel folder.   Using catkin_package and find_package(catkin ... ) will set up all the paths correctly for that to work.  We use this setup on a number of ROS projects, so it is not a non-standard approach.

Manually listing a library from another ROS package will require that package to be in a common library path, which defeats the purpose of having the ROS catkin  workspace that is set up for different projects.  Catkin creates a setup.bash in the devel folder of the catkin workspace that updates the appropriate paths including $ROS_PACKAGE_PATH

**Comment by finger563** [comment] 2017-07-05 19:10
@dcconner we have used the catkin env vars in our CMakeLists for each part of ROSMOD to select the proper place to install to

**Comment by finger563** [comment] 2017-07-05 19:48
@dcconner @HaleyCurr  since we've not used catkin tools in the past, do you have ideas on how to properly install our shared objects and our one binary such that it would work on your system?  If I understand correctly, our use of the catkin env vars should handle this, but apparently is not on your system.

**Comment by finger563** [comment] 2017-08-15 16:03
Should be closed now that we've moved to `catkin build` per #6 and #5

**Closed as completed by finger563** 2017-08-15 16:03 UTC
Labels: bug
